# redirect to english or italian landing pages.

[[redirects]]
from = "/"
to = "/it"
status = 302
force = true
conditions = {Language = ["it"]}

[[redirects]]
from = "/"
to = "/en"
status = 302
force = true

[[headers]]
    for = "/*"
    [headers.values]
    Content-Security-Policy = "*.plausible.io; upgrade-insecure-requests; block-all-mixed-content;" 
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"

[build]
	publish = "_site"
	command = "npm run build"