# redirect to italian or english landing pages

[[redirects]]
  from = "/*"
  to = "/en"
  status = 302
  force= true
  conditions = {Language = ["en"]}

[[redirects]]
	from = "/*"
	to = "/it"
	status = 302
	force = true
	conditions = {Language = ["it"]}

[[redirects]]
	from = "/*"
	to = "/it"
	status = 302
	force = true

[[headers]]
    for = "/*"
    [headers.values]
    Content-Security-Policy = "upgrade-insecure-requests; block-all-mixed-content;"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "autoplay=(), camera=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), publickey-credentials-get=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"

[build]
	publish = "_site"
	command = "npm run build"

[[plugins]]

	# Opt-in to the Netlify Lighthouse plugin (choose one):

	# 1. Go to your site on https://app.netlify.com and navigate to the Integrations tab, search for the `Lighthouse` plugin
	# 2. Or via `npm install -D @netlify/plugin-lighthouse`

	# Read more: https://github.com/netlify/netlify-plugin-lighthouse

	package = "@netlify/plugin-lighthouse"

	# optional, fails build when a category is below a threshold
	[plugins.inputs.thresholds]
		performance = 0.1
		accessibility = 0.1
		best-practices = 0.1
		seo = 0.1

	[plugins.inputs]
		output_path = "reports/lighthouse/index.html"
